sudo: required
dist: trusty
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: 
        - COMPILER=g++-5
        - OMP_NUM_THREADS=4
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
            - libiomp-dev
      env: 
        - COMPILER=clang++-3.7
        - OMP_NUM_THREADS=4
before_install:
  - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
script:
  - git clone https://github.com/nickbruun/hayai.git
  - cd hayai
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - git clone https://github.com/google/googletest.git
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBUILD_TESTS=ON -DBUILD_BENCHMARKS=ON -Dhayai_DIR=../../hayai/build ..
  - make
  - octreebuilder/unittests/octreebuilder-unittests
  - octreebuilder/integrationtests/octreebuilder-integrationtests  
