dist: precise
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: 
        - COMPILER=g++-5
        - OMP_NUM_THREADS=4
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - OMP_NUM_THREADS=4
script:
  - git clone https://github.com/nickbruun/hayai.git
  - cd hayai
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - git clone https://github.com/google/googletest.git
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBUILD_TESTS=ON -DBUILD_BENCHMARKS=ON -DLINK_INTEL_OPENMP=OFF -Dhayai_DIR=../../hayai/build ..
  - make
  - octreebuilder/unittests/octreebuilder-unittests
  - octreebuilder/integrationtests/octreebuilder-integrationtests  
